// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iszsqkyhhydpzszjvpng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzenNxa3loaHlkcHpzemp2cG5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MjQ1NjUsImV4cCI6MjA2NzMwMDU2NX0.DAWZZQc1x7kthrs3HNjnXYKSSP8cuVpG2TGyORlfu9A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});